import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";
import { loadSettings } from "@/lib/local-radar";
import { supabase } from "@/lib/supabase";

export default function CreateCommunityScreen() {
  const colors = useColors(); const { user } = useSupabaseAuth(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState("General"); const [visibility, setVisibility] = useState<"public" | "private">("public"); const [saving, setSaving] = useState(false);
  const create = async () => { if (!user || !supabase) return; const cleanName = name.trim(); if (cleanName.length < 3) { Alert.alert("Community name", "Use at least 3 characters."); return; } setSaving(true); try { const settings = await loadSettings(); const result = await supabase.from("communities").insert({ name: cleanName, description: description.trim(), area: settings.area, category, visibility, rules: [], created_by: user.id }).select("id").single(); if (result.error) throw result.error; await supabase.from("community_members").upsert({ community_id: result.data.id, user_id: user.id, is_moderator: true }, { onConflict: "community_id,user_id" }); router.replace({ pathname: "/community/[id]", params: { id: result.data.id } } as never); } catch (error) { Alert.alert("Couldn't create community", error instanceof Error ? error.message : "Please try again."); } finally { setSaving(false); } };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>CREATE A GROUP</Text><Text style={[styles.title, { color: colors.foreground }]}>Build your local community</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Like a Facebook group, but focused on your local area.</Text><Text style={[styles.label, { color: colors.muted }]}>NAME</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Bellville Neighbours" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]} /><Text style={[styles.label, { color: colors.muted }]}>DESCRIPTION</Text><TextInput multiline value={description} onChangeText={setDescription} placeholder="What is this community for?" placeholderTextColor={colors.muted} style={[styles.input, styles.multiline, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]} /><Text style={[styles.label, { color: colors.muted }]}>CATEGORY</Text><View style={styles.options}>{["General", "Neighbourhood", "Business", "Buy & Sell", "Events", "Sports"].map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.option, { borderColor: category === item ? colors.primary : colors.border, backgroundColor: category === item ? `${colors.primary}18` : colors.surface }]}><Text style={{ color: category === item ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{item}</Text></Pressable>)}</View><Text style={[styles.label, { color: colors.muted }]}>VISIBILITY</Text><View style={styles.options}>{(["public", "private"] as const).map((item) => <Pressable key={item} onPress={() => setVisibility(item)} style={[styles.option, { borderColor: visibility === item ? colors.primary : colors.border, backgroundColor: visibility === item ? `${colors.primary}18` : colors.surface }]}><Text style={{ color: visibility === item ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{item === "public" ? "Public — anyone can join" : "Private — members only"}</Text></Pressable>)}</View><Pressable disabled={saving} onPress={create} style={[styles.button, { backgroundColor: colors.primary, opacity: saving ? 0.6 : 1 }]}><Text style={styles.buttonText}>{saving ? "Creating…" : "Create community"}</Text></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 80 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.1 }, title: { fontSize: 28, fontWeight: "900", marginTop: 7 }, subtitle: { fontSize: 13, lineHeight: 18, marginTop: 5 }, label: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginTop: 22, marginBottom: 8 }, input: { minHeight: 50, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 14 }, multiline: { minHeight: 120, paddingTop: 14, textAlignVertical: "top" }, options: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, option: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 11, paddingVertical: 10 }, button: { minHeight: 52, borderRadius: 17, alignItems: "center", justifyContent: "center", marginTop: 28 }, buttonText: { color: "#10211D", fontSize: 15, fontWeight: "900" } });
