import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { composeBusinessInvitationEmail, createBusinessInvitation, type BusinessInviteRole } from "@/lib/business-invitations";
import { loadMyBusinessProfile } from "@/lib/account-repository";

export default function BusinessTeamScreen() {
  const colors = useColors();
  const { businessId } = useLocalSearchParams<{ businessId?: string }>();
  const [businessName, setBusinessName] = useState("your business"); const [email, setEmail] = useState(""); const [role, setRole] = useState<BusinessInviteRole>("staff"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!businessId) return; void loadMyBusinessProfile(businessId).then(({ data }) => { const business = data?.businesses ? (Array.isArray(data.businesses) ? data.businesses[0] : data.businesses) : null; if (business?.name) setBusinessName(business.name); }); }, [businessId]);
  const invite = async () => { if (!businessId) { setError("Choose a business profile before inviting a team member."); return; } setBusy(true); setError(null); setMessage(null); const created = await createBusinessInvitation(businessId, email, role); if (created.error || !created.data) { setBusy(false); setError(created.error?.message ?? "We couldn’t create this invitation."); return; } const composed = await composeBusinessInvitationEmail(email.trim(), created.data.business_name, role, created.data.token); setBusy(false); if (composed.status === "unavailable") { setMessage(`Invitation created. Copy this secure link into your preferred email app: ${composed.link}`); return; } setMessage("Invitation created. Your device opened an email draft with the secure invitation link."); setEmail(""); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.right" size={22} color={colors.foreground} style={styles.backIcon} /><Text style={[styles.backText, { color: colors.foreground }]}>Business profile</Text></Pressable><Text style={[styles.eyebrow, { color: colors.primary }]}>BUSINESS TEAM</Text><Text style={[styles.title, { color: colors.foreground }]}>Invite trusted people.</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Invitees sign in with the exact email address you choose. You can give them admin access to manage the profile, or staff access for future assigned work.</Text><View style={[styles.businessCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="briefcase.fill" size={19} color={colors.primary} /><Text style={[styles.businessText, { color: colors.foreground }]}>{businessName}</Text></View><Text style={[styles.label, { color: colors.muted }]}>EMAIL ADDRESS</Text><TextInput value={email} onChangeText={setEmail} placeholder="teammate@example.com" autoCapitalize="none" keyboardType="email-address" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]} /><Text style={[styles.label, { color: colors.muted }]}>ROLE</Text><View style={styles.roleGroup}><RoleCard selected={role === "admin"} onPress={() => setRole("admin")} title="Admin" detail="Can update the business profile and manage future team workflows." colors={colors} /><RoleCard selected={role === "staff"} onPress={() => setRole("staff")} title="Staff" detail="A recognised team member, ready for future assigned business tasks." colors={colors} /></View>{error ? <Text accessibilityRole="alert" style={[styles.error, { color: colors.error }]}>{error}</Text> : null}{message ? <Text accessibilityRole="alert" selectable style={[styles.message, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}>{message}</Text> : null}<Pressable accessibilityRole="button" disabled={busy} onPress={() => void invite()} style={({ pressed }) => [styles.primary, { backgroundColor: colors.primary, opacity: busy ? 0.55 : pressed ? 0.8 : 1 }]}>{busy ? <ActivityIndicator color="#10211D" /> : <Text style={styles.primaryText}>Create invitation email</Text>}</Pressable></ScrollView></ScreenContainer>;
}

function RoleCard({ selected, onPress, title, detail, colors }: { selected: boolean; onPress: () => void; title: string; detail: string; colors: ReturnType<typeof useColors> }) { return <Pressable accessibilityRole="radio" accessibilityState={{ selected }} onPress={onPress} style={[styles.roleCard, { backgroundColor: selected ? `${colors.primary}18` : colors.surface, borderColor: selected ? colors.primary : colors.border }]}><Text style={[styles.roleTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.roleDetail, { color: colors.muted }]}>{detail}</Text></Pressable>; }

const styles = StyleSheet.create({ content: { padding: 24, paddingBottom: 44 }, back: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 28 }, backIcon: { transform: [{ rotate: "180deg" }] }, backText: { fontSize: 14, fontWeight: "700" }, eyebrow: { fontSize: 11, letterSpacing: 1.2, fontWeight: "900" }, title: { fontSize: 30, lineHeight: 37, fontWeight: "900", marginTop: 9 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 8 }, businessCard: { borderWidth: 1, borderRadius: 15, padding: 13, flexDirection: "row", gap: 8, alignItems: "center", marginTop: 19 }, businessText: { fontSize: 13, fontWeight: "900" }, label: { fontSize: 10, letterSpacing: 1.1, fontWeight: "900", marginTop: 19, marginBottom: 7 }, input: { minHeight: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 15 }, roleGroup: { gap: 8 }, roleCard: { borderWidth: 1, borderRadius: 15, padding: 13 }, roleTitle: { fontSize: 13, fontWeight: "900" }, roleDetail: { fontSize: 11, lineHeight: 16, marginTop: 3 }, error: { fontSize: 13, lineHeight: 18, fontWeight: "700", marginTop: 16 }, message: { fontSize: 12, lineHeight: 18, borderWidth: 1, borderRadius: 14, padding: 12, marginTop: 16 }, primary: { minHeight: 54, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 22 }, primaryText: { color: "#10211D", fontSize: 14, fontWeight: "900" } });
