import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";
import { listMyConversations, listConversationMessages, markConversationRead, sendDirectMessage, subscribeToConversation, type Conversation, type DirectMessage } from "@/lib/messaging";

export default function MessagesScreen() {
  const colors = useColors(); const { isAuthenticated } = useSupabaseAuth(); const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<Conversation | null>(null); const [messages, setMessages] = useState<DirectMessage[]>([]); const [text, setText] = useState("");
  const loadConversations = async () => { const result = await listMyConversations(); if (!result.error) setConversations(result.data); };
  useEffect(() => { if (isAuthenticated) void loadConversations(); }, [isAuthenticated]);
  useEffect(() => { if (!selected) return; let active = true; const load = async () => { const result = await listConversationMessages(selected.id); if (active && !result.error) setMessages(result.data); await markConversationRead(selected.id); }; void load(); const stop = subscribeToConversation(selected.id, () => { void load(); }); return () => { active = false; stop(); }; }, [selected?.id]);
  if (!isAuthenticated) return <ScreenContainer><View style={styles.center}><Text style={[styles.title, { color: colors.foreground }]}>Sign in to use messages</Text></View></ScreenContainer>;
  if (selected) return <ScreenContainer><View style={styles.header}><Pressable onPress={() => setSelected(null)}><IconSymbol name="chevron.left" size={22} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>{selected.other_profile?.display_name ?? "Conversation"}</Text><View style={{ width: 22 }} /></View><ScrollView contentContainerStyle={styles.thread}>{messages.map((message) => <View key={message.id} style={[styles.bubble, { alignSelf: message.sender_id === selected.other_profile?.id ? "flex-start" : "flex-end", backgroundColor: message.sender_id === selected.other_profile?.id ? colors.surface : colors.primary, borderColor: colors.border }]}><Text style={{ color: message.sender_id === selected.other_profile?.id ? colors.foreground : "#10211D" }}>{message.body}</Text></View>)}</ScrollView><View style={[styles.composer, { borderColor: colors.border, backgroundColor: colors.surface }]}><TextInput value={text} onChangeText={setText} placeholder="Write a message…" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /><Pressable onPress={async () => { const result = await sendDirectMessage(selected.id, text); if (!result.error) { setText(""); setMessages((current) => [...current, result.data!]); } }}><IconSymbol name="arrow.up.circle.fill" size={30} color={colors.primary} /></Pressable></View></ScreenContainer>;
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={22} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Messages</Text><View style={{ width: 22 }} /></View>{conversations.length === 0 ? <View style={styles.center}><IconSymbol name="message.fill" size={32} color={colors.muted} /><Text style={[styles.title, { color: colors.foreground }]}>No messages yet</Text><Text style={[styles.body, { color: colors.muted }]}>When someone messages you, the conversation will appear here.</Text></View> : conversations.map((conversation) => <Pressable key={conversation.id} onPress={() => setSelected(conversation)} style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={styles.avatarText}>{conversation.other_profile?.display_name?.slice(0, 1).toUpperCase() ?? "?"}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{conversation.other_profile?.display_name ?? "Lekka user"}</Text><Text style={[styles.body, { color: colors.muted }]}>{conversation.other_profile?.username ? `@${conversation.other_profile.username}` : "Private conversation"}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 10 }, headerTitle: { fontSize: 18, fontWeight: "900" }, row: { flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderRadius: 17, padding: 13, marginTop: 9 }, avatar: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#10211D", fontWeight: "900" }, name: { fontSize: 14, fontWeight: "800" }, body: { fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 4 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, title: { fontSize: 19, fontWeight: "900", marginTop: 10 }, thread: { padding: 16, gap: 8, flexGrow: 1, justifyContent: "flex-end" }, bubble: { maxWidth: "78%", borderWidth: 1, borderRadius: 17, paddingHorizontal: 13, paddingVertical: 10 }, composer: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 18, padding: 7, margin: 10 }, input: { flex: 1, minHeight: 42, paddingHorizontal: 10 } });
