import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { AuthGate } from "@/components/auth-gate";
import { useColors } from "@/hooks/use-colors";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";
import { listNotifications, markNotificationRead } from "@/lib/social-repository";

export default function NotificationsScreen() {
  const colors = useColors();
  const { isAuthenticated } = useSupabaseAuth();
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [authGateAction, setAuthGateAction] = useState<string | null>(null);
  useEffect(() => { if (!isAuthenticated) { setLoading(false); return; } let mounted = true; void listNotifications().then((result) => { if (mounted) setItems(result.data); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [isAuthenticated]);
  if (!isAuthenticated) return <ScreenContainer><View style={styles.center}>{authGateAction && <AuthGate action={authGateAction} onCancel={() => setAuthGateAction(null)} />}<IconSymbol name="bell.fill" size={38} color={colors.primary} /><Text style={[styles.title, { color: colors.foreground }]}>Your local updates</Text><Text style={[styles.body, { color: colors.muted }]}>Join Lekka to see follows, comments, and reactions.</Text><Pressable accessibilityRole="button" onPress={() => setAuthGateAction("view notifications")} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Join Lekka</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><Pressable accessibilityRole="button" accessibilityLabel="Go back from notifications" onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.right" size={20} color={colors.foreground} style={styles.backIcon} /><Text style={[styles.backText, { color: colors.foreground }]}>Notifications</Text></Pressable><Text style={[styles.pageTitle, { color: colors.foreground }]}>Your local updates</Text>{loading ? <Text style={[styles.body, { color: colors.muted }]}>Loading notifications…</Text> : items.length === 0 ? <View style={styles.empty}><IconSymbol name="bell.fill" size={30} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>You’re all caught up.</Text><Text style={[styles.body, { color: colors.muted }]}>New activity from your local network will appear here.</Text></View> : items.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`${item.title}. ${item.body}`} onPress={() => { void markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, read_at: new Date().toISOString() } : entry)); if (item.target_type === "post" && item.target_id) router.push({ pathname: "/post/[id]", params: { id: item.target_id } } as never); if (item.target_type === "profile" && item.target_id) router.push({ pathname: "/public-profile/[id]", params: { id: item.target_id } } as never); }} style={[styles.notification, { backgroundColor: item.read_at ? colors.surface : `${colors.primary}12`, borderColor: colors.border }]}><View style={[styles.dot, { backgroundColor: item.read_at ? colors.border : colors.primary }]} /><View style={styles.copy}><Text style={[styles.notificationTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.body, { color: colors.muted }]}>{item.body}</Text><Text style={[styles.time, { color: colors.muted }]}>{new Date(item.created_at).toLocaleString()}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 24, paddingBottom: 50 }, back: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 24 }, backIcon: { transform: [{ rotate: "180deg" }] }, backText: { fontSize: 14, fontWeight: "800" }, pageTitle: { fontSize: 28, fontWeight: "900", marginBottom: 18 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, title: { fontSize: 24, fontWeight: "900", marginTop: 16, textAlign: "center" }, body: { fontSize: 13, lineHeight: 19, marginTop: 5 }, primary: { minHeight: 50, minWidth: 160, borderRadius: 15, alignItems: "center", justifyContent: "center", marginTop: 20 }, primaryText: { color: "#10211D", fontWeight: "900" }, empty: { alignItems: "center", paddingVertical: 70 }, emptyTitle: { fontSize: 17, fontWeight: "900", marginTop: 12 }, notification: { minHeight: 64, flexDirection: "row", alignItems: "center", borderWidth: 1, borderRadius: 17, padding: 14, marginBottom: 9 }, dot: { width: 9, height: 9, borderRadius: 5, marginRight: 12 }, copy: { flex: 1 }, notificationTitle: { fontSize: 14, fontWeight: "900" }, time: { fontSize: 10, marginTop: 7 },
});
