import { useEffect, useState } from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { getBusiness } from "@/lib/local-directory";

type Business = { id: string; name: string; category: string; description: string | null; area: string; address: string | null; phone: string | null; whatsapp: string | null; website: string | null; opening_hours: string | null; verification_state: string | null };

export default function LocalDetailScreen() {
  const colors = useColors();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [business, setBusiness] = useState<Business | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; if (!id) return () => { active = false; }; void getBusiness(id).then((result) => { if (active) setBusiness(result.data as Business | null); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]);
  if (loading) return <ScreenContainer><View style={styles.center}><Text style={[styles.status, { color: colors.muted }]}>Loading listing…</Text></View></ScreenContainer>;
  if (!business) return <ScreenContainer><View style={styles.center}><Text style={[styles.status, { color: colors.foreground }]}>This listing is no longer available.</Text><Pressable onPress={() => router.back()}><Text style={[styles.link, { color: colors.primary }]}>Go back</Text></Pressable></View></ScreenContainer>;
  const call = business.phone ? () => void Linking.openURL(`tel:${business.phone}`) : undefined;
  const openWebsite = business.website ? () => void Linking.openURL(business.website!.startsWith("http") ? business.website! : `https://${business.website}`) : undefined;
  const openWhatsapp = business.whatsapp ? () => void Linking.openURL(`https://wa.me/${business.whatsapp!.replace(/[^0-9]/g, "")}`) : undefined;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.right" size={20} color={colors.foreground} style={styles.backIcon} /><Text style={[styles.backText, { color: colors.foreground }]}>Local</Text></Pressable><View style={[styles.icon, { backgroundColor: `${colors.primary}22` }]}><IconSymbol name="building.2.fill" size={31} color={colors.primary} /></View><Text style={[styles.eyebrow, { color: colors.primary }]}>{business.verification_state === "verified" ? "VERIFIED LOCAL" : "LOCAL LISTING"}</Text><Text style={[styles.title, { color: colors.foreground }]}>{business.name}</Text><Text style={[styles.meta, { color: colors.muted }]}>{business.category} · {business.area}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>About</Text><Text style={[styles.body, { color: colors.muted }]}>{business.description || "This listing has not added a description yet."}</Text></View>{business.address && <InfoRow colors={colors} icon="location.fill" text={business.address} />}{business.opening_hours && <InfoRow colors={colors} icon="clock.fill" text={business.opening_hours} />}{(call || openWebsite || openWhatsapp) && <View style={styles.actions}>{call && <Pressable onPress={call} style={[styles.action, { backgroundColor: colors.primary }]}><IconSymbol name="message.fill" size={18} color={colors.background} /><Text style={[styles.actionText, { color: colors.background }]}>Call</Text></Pressable>}{openWebsite && <Pressable onPress={openWebsite} style={[styles.action, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="arrow.up.right" size={18} color={colors.foreground} /><Text style={[styles.actionText, { color: colors.foreground }]}>Website</Text></Pressable>}{openWhatsapp && <Pressable onPress={openWhatsapp} style={[styles.action, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="message.fill" size={18} color={colors.foreground} /><Text style={[styles.actionText, { color: colors.foreground }]}>WhatsApp</Text></Pressable>}</View>}<View style={[styles.empty, { borderColor: colors.border }]}><IconSymbol name="bubble.left.fill" size={26} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>More local activity will appear here</Text><Text style={[styles.body, { color: colors.muted }]}>Offers, events, and community updates from this listing will be shown when published.</Text></View></ScrollView></ScreenContainer>;
}

function InfoRow({ colors, icon, text }: { colors: ReturnType<typeof useColors>; icon: "location.fill" | "clock.fill"; text: string }) { return <View style={[styles.info, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name={icon} size={17} color={colors.primary} /><Text style={[styles.infoText, { color: colors.muted }]}>{text}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 42 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, padding: 24 }, status: { fontSize: 16, fontWeight: "800", textAlign: "center" }, link: { fontWeight: "800" }, back: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 22 }, backIcon: { transform: [{ rotate: "180deg" }] }, backText: { fontSize: 14, fontWeight: "800" }, icon: { width: 72, height: 72, borderRadius: 23, alignItems: "center", justifyContent: "center", marginBottom: 18 }, eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1 }, title: { fontSize: 28, lineHeight: 34, fontWeight: "900", marginTop: 6 }, meta: { fontSize: 13, marginTop: 5 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, marginTop: 20 }, cardTitle: { fontSize: 16, fontWeight: "900" }, body: { fontSize: 14, lineHeight: 21, marginTop: 7 }, info: { borderWidth: 1, borderRadius: 15, padding: 13, flexDirection: "row", alignItems: "center", gap: 9, marginTop: 10 }, infoText: { flex: 1, fontSize: 13 }, actions: { flexDirection: "row", gap: 10, marginTop: 17 }, action: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 11, flexDirection: "row", alignItems: "center", gap: 7 }, actionText: { fontSize: 13, fontWeight: "800" }, empty: { borderWidth: 1, borderStyle: "dashed", borderRadius: 18, padding: 21, alignItems: "center", gap: 7, marginTop: 20 }, emptyTitle: { fontSize: 15, fontWeight: "800", textAlign: "center" },
});
