import { Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";

const categories = [{ label: "Businesses", icon: "building.2.fill" as const, caption: "Find trusted local places", color: "#2F7D67" }, { label: "Deals", icon: "tag.fill" as const, caption: "Good value, close by", color: "#E9A23B" }, { label: "Events", icon: "calendar" as const, caption: "Plans for your area", color: "#5E6AD2" }, { label: "Marketplace", icon: "cart.fill" as const, caption: "Buy and sell nearby", color: "#8A6A4A" }, { label: "Jobs", icon: "briefcase.fill" as const, caption: "Work in your city", color: "#D95D4F" }, { label: "Services", icon: "wrench.and.screwdriver.fill" as const, caption: "People who can help", color: "#4E8D8A" }];

export default function LocalScreen() { const colors = useColors(); return <ScreenContainer><View style={styles.content}><Text style={[styles.eyebrow, { color: colors.primary }]}>LOCAL LIFE</Text><Text style={[styles.title, { color: colors.foreground }]}>Useful around you</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Discover the people, places, and opportunities that keep Bellville moving.</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="magnifyingglass" size={19} color={colors.muted} /><Text style={[styles.searchText, { color: colors.muted }]}>Search businesses, deals, events…</Text></View><View style={styles.grid}>{categories.map((item) => <Pressable key={item.label} style={[styles.category, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.categoryIcon, { backgroundColor: `${item.color}20` }]}><IconSymbol name={item.icon} size={23} color={item.color} /></View><Text style={[styles.categoryLabel, { color: colors.foreground }]}>{item.label}</Text><Text style={[styles.categoryCaption, { color: colors.muted }]}>{item.caption}</Text></Pressable>)}</View><View style={[styles.featured, { backgroundColor: colors.foreground }]}><View style={styles.featuredTop}><View style={styles.featuredBadge}><IconSymbol name="checkmark.seal.fill" size={16} color="#E9A23B" /><Text style={styles.featuredBadgeText}>TRUSTED LOCAL</Text></View><IconSymbol name="arrow.up.right" size={20} color="#E9A23B" /></View><Text style={[styles.featuredTitle, { color: colors.background }]}>Support the places that support your area.</Text><Text style={[styles.featuredText, { color: `${colors.background}AA` }]}>Verified businesses can share updates, offers, jobs, and events directly with nearby customers.</Text></View></View></ScreenContainer>; }

const styles = StyleSheet.create({ content: { padding: 20 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.1 }, title: { fontSize: 28, fontWeight: "800", marginTop: 6 }, subtitle: { fontSize: 13, lineHeight: 18, marginTop: 5 }, search: { borderWidth: 1, borderRadius: 16, height: 48, marginTop: 19, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 9 }, searchText: { fontSize: 14 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 19 }, category: { width: "48.3%", borderWidth: 1, borderRadius: 18, padding: 14, minHeight: 128 }, categoryIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", marginBottom: 13 }, categoryLabel: { fontSize: 14, fontWeight: "800" }, categoryCaption: { fontSize: 11, lineHeight: 15, marginTop: 4 }, featured: { borderRadius: 20, padding: 17, marginTop: 20 }, featuredTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, featuredBadge: { flexDirection: "row", alignItems: "center", gap: 6 }, featuredBadgeText: { color: "#E9A23B", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, featuredTitle: { fontSize: 18, lineHeight: 24, fontWeight: "800", marginTop: 18 }, featuredText: { fontSize: 12, lineHeight: 18, marginTop: 7 },
});
