import { useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View, type DimensionValue } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { RadarCategory, RadarItem, seededRadar, loadSettings, saveSettings } from "@/lib/local-radar";
import { fetchNearbyItems } from "@/lib/supabase-repository";
import { requestApproximateLocation } from "@/lib/location";
import { useColors } from "@/hooks/use-colors";

const categories: Array<RadarCategory | "All"> = ["All", "Food", "Event", "Deal", "Job", "Marketplace", "Alert", "Service"];
const radiusOptions = ["500 m", "1 km", "5 km", "10 km", "City"];

export default function NearbyScreen() {
  const colors = useColors();
  const [category, setCategory] = useState<RadarCategory | "All">("All");
  const [radius, setRadius] = useState("5 km");
  const [mapView, setMapView] = useState(false);
  const [locationStatus, setLocationStatus] = useState<"manual" | "granted" | "denied">("manual");
  const [radarItems, setRadarItems] = useState<RadarItem[]>(seededRadar);
  const useCurrentLocation = async () => { const result = await requestApproximateLocation("Bellville"); setLocationStatus(result.status === "granted" ? "granted" : "denied"); };
  useEffect(() => { void loadSettings().then((settings) => { setRadius(settings.radius); return fetchNearbyItems(settings); }).then((remote) => { if (remote.length) setRadarItems(remote); }); }, []);
  const setDiscoveryRadius = (nextRadius: string) => { setRadius(nextRadius); void loadSettings().then((settings) => saveSettings({ ...settings, radius: nextRadius })); };
  const items = useMemo(() => category === "All" ? radarItems : radarItems.filter((item) => item.category === category), [category, radarItems]);
  return <ScreenContainer><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<>
    <View style={styles.titleRow}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>LOCAL RADAR</Text><Text style={[styles.title, { color: colors.foreground }]}>Around Bellville</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Privacy-safe areas, not exact user locations.</Text><Pressable onPress={useCurrentLocation} style={styles.locationAction}><IconSymbol name="location.fill" size={14} color={colors.primary} /><Text style={[styles.locationActionText, { color: colors.primary }]}>{locationStatus === "granted" ? "Using approximate location" : locationStatus === "denied" ? "Using Bellville manually" : "Use current area"}</Text></Pressable></View><Pressable onPress={() => setMapView(!mapView)} style={[styles.viewToggle, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name={mapView ? "list.bullet" : "map.fill"} size={18} color={colors.foreground} /><Text style={[styles.toggleText, { color: colors.foreground }]}>{mapView ? "List" : "Map"}</Text></Pressable></View>
    <View style={[styles.mapPreview, { backgroundColor: mapView ? "#DCE8DF" : colors.surface, borderColor: colors.border }]}>{mapView ? <><View style={styles.mapRoadOne} /><View style={styles.mapRoadTwo} /><RadarPin x="26%" y="38%" color="#D95D4F" /><RadarPin x="56%" y="56%" color="#E9A23B" /><RadarPin x="73%" y="27%" color="#2F7D67" /><Text style={styles.mapLabel}>Approximate local activity</Text></> : <><IconSymbol name="location.fill" size={28} color={colors.primary} /><Text style={[styles.mapTitle, { color: colors.foreground }]}>See what matters around you</Text><Text style={[styles.mapSub, { color: colors.muted }]}>Switch to Map to explore category markers.</Text></>}</View>
    <Text style={[styles.filterLabel, { color: colors.muted }]}>DISCOVERY RADIUS</Text><FlatList data={radiusOptions} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.radiusRow} keyExtractor={(item) => item} renderItem={({ item }) => <Pressable onPress={() => setDiscoveryRadius(item)} style={[styles.radius, { borderColor: radius === item ? colors.primary : colors.border, backgroundColor: radius === item ? `${colors.primary}18` : colors.surface }]}><Text style={[styles.radiusText, { color: radius === item ? colors.primary : colors.muted }]}>{item}</Text></Pressable>} />
    <Text style={[styles.filterLabel, { color: colors.muted }]}>EXPLORE BY CATEGORY</Text><FlatList data={categories} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRow} keyExtractor={(item) => item} renderItem={({ item }) => <Pressable onPress={() => setCategory(item)} style={[styles.category, { backgroundColor: category === item ? colors.foreground : colors.surface, borderColor: colors.border }]}><Text style={[styles.categoryText, { color: category === item ? colors.background : colors.muted }]}>{item}</Text></Pressable>} />
    <View style={styles.resultRow}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Nearby now</Text><Text style={[styles.resultMeta, { color: colors.muted }]}>{items.length} results · {radius}</Text></View>
  </>} renderItem={({ item }) => <RadarCard item={item} colors={colors} />} /> </ScreenContainer>;
}

function RadarPin({ x, y, color }: { x: DimensionValue; y: DimensionValue; color: string }) { return <View style={[styles.pin, { left: x, top: y, backgroundColor: color }]}><IconSymbol name="location.fill" size={17} color="#FFF" /></View>; }
function RadarCard({ item, colors }: { item: RadarItem; colors: ReturnType<typeof useColors> }) { return <Pressable style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.itemIcon, { backgroundColor: `${item.accent}20` }]}><IconSymbol name={item.icon === "restaurant" ? "building.2.fill" : item.category === "Alert" ? "exclamationmark.triangle.fill" : item.category === "Event" ? "calendar" : item.category === "Job" ? "briefcase.fill" : item.category === "Marketplace" ? "cart.fill" : "tag.fill"} size={22} color={item.accent} /></View><View style={styles.cardCopy}><View style={styles.cardTitleRow}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{item.title}</Text><IconSymbol name="chevron.right" size={18} color={colors.muted} /></View><Text style={[styles.cardSub, { color: colors.muted }]}>{item.subtitle}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{item.area} · {item.distance} · {item.time}</Text></View></Pressable>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 30 }, locationAction: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 9 }, locationActionText: { fontSize: 11, fontWeight: "700" }, titleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 17 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 28, lineHeight: 34, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 13, marginTop: 4 }, viewToggle: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderRadius: 14, paddingHorizontal: 11, paddingVertical: 9 }, toggleText: { fontSize: 12, fontWeight: "700" }, mapPreview: { height: 190, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center", overflow: "hidden" }, mapTitle: { marginTop: 10, fontSize: 16, fontWeight: "800" }, mapSub: { marginTop: 5, fontSize: 12 }, mapRoadOne: { position: "absolute", width: "120%", height: 14, backgroundColor: "#FFFFFF88", transform: [{ rotate: "22deg" }] }, mapRoadTwo: { position: "absolute", width: "120%", height: 10, backgroundColor: "#FFFFFF88", transform: [{ rotate: "-34deg" }] }, mapLabel: { position: "absolute", bottom: 13, fontSize: 11, color: "#426154", fontWeight: "700" }, pin: { position: "absolute", width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: "#FFFFFF" }, filterLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginTop: 20 }, radiusRow: { gap: 7, paddingTop: 9 }, radius: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8 }, radiusText: { fontSize: 12, fontWeight: "700" }, categoryRow: { gap: 7, paddingTop: 9 }, category: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, paddingVertical: 9 }, categoryText: { fontSize: 12, fontWeight: "700" }, resultRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 24, marginBottom: 12 }, sectionTitle: { fontSize: 18, fontWeight: "800" }, resultMeta: { fontSize: 12 }, card: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 10 }, itemIcon: { width: 48, height: 48, borderRadius: 15, alignItems: "center", justifyContent: "center", marginRight: 12 }, cardCopy: { flex: 1 }, cardTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardSub: { fontSize: 13, marginTop: 3 }, cardMeta: { fontSize: 11, marginTop: 8 },
});
