import { Pressable, StyleSheet, Text, View } from "react-native";

import { AuthGate } from "@/components/auth-gate";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useSupabaseAuth } from "@/hooks/use-supabase-auth";

const communities = [{ name: "Bellville Neighbours", members: "2.4k members", color: "#2F7D67" }, { name: "Cape Town Weekend Plans", members: "8.1k members", color: "#5E6AD2" }, { name: "Local Makers & Small Business", members: "1.2k members", color: "#E9A23B" }];

export default function SocialScreen() {
  const colors = useColors();
  const { isAuthenticated } = useSupabaseAuth();
  const [authGateAction, setAuthGateAction] = React.useState<string | null>(null);
  return <ScreenContainer><View style={styles.content}>{authGateAction && <AuthGate action={authGateAction} onCancel={() => setAuthGateAction(null)} />}<View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>YOUR PEOPLE</Text><Text style={[styles.title, { color: colors.foreground }]}>Social</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Communities that make your area feel like home.</Text></View><Pressable onPress={() => { if (!isAuthenticated) setAuthGateAction("message people"); }} accessibilityLabel="Messages" style={[styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="message.fill" size={21} color={colors.foreground} /></Pressable></View><View style={styles.segment}><Text style={[styles.segmentActive, { color: colors.foreground, borderBottomColor: colors.primary }]}>Communities</Text><Text style={[styles.segmentText, { color: colors.muted }]}>Following</Text><Text style={[styles.segmentText, { color: colors.muted }]}>Messages</Text></View><View style={[styles.invite, { backgroundColor: colors.foreground }]}><View style={styles.inviteIcon}><IconSymbol name="person.3.fill" size={22} color={colors.foreground} /></View><View style={styles.inviteCopy}><Text style={[styles.inviteTitle, { color: colors.background }]}>Find your local people</Text><Text style={[styles.inviteText, { color: `${colors.background}AA` }]}>Join conversations about places, events, and everyday life nearby.</Text></View><IconSymbol name="chevron.right" size={20} color={colors.background} /></View><View style={styles.sectionRow}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Your communities</Text><Text style={[styles.seeAll, { color: colors.primary }]}>See all</Text></View>{communities.map((community) => <Pressable key={community.name} onPress={() => { if (!isAuthenticated) setAuthGateAction("join communities"); }} style={[styles.community, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.communityIcon, { backgroundColor: community.color }]}><Text style={styles.communityInitial}>{community.name.slice(0, 1)}</Text></View><View style={styles.communityCopy}><Text style={[styles.communityName, { color: colors.foreground }]}>{community.name}</Text><Text style={[styles.communityMeta, { color: colors.muted }]}>{community.members}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>)}<Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 25 }]}>Recent conversations</Text><View style={[styles.empty, { borderColor: colors.border }]}><IconSymbol name="message.fill" size={26} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Messages will live here</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Start a conversation from a profile or local listing.</Text></View></View></ScreenContainer>;
}

import React from "react";
const styles = StyleSheet.create({ content: { padding: 20 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.1 }, title: { fontSize: 28, fontWeight: "800", marginTop: 6 }, subtitle: { fontSize: 13, marginTop: 5, maxWidth: 280, lineHeight: 18 }, iconButton: { borderWidth: 1, borderRadius: 14, padding: 10 }, segment: { flexDirection: "row", gap: 22, borderBottomWidth: 1, borderBottomColor: "#DDE5DF", marginTop: 23 }, segmentActive: { fontSize: 13, fontWeight: "800", paddingBottom: 11, borderBottomWidth: 2 }, segmentText: { fontSize: 13, fontWeight: "700", paddingBottom: 11 }, invite: { borderRadius: 20, padding: 16, flexDirection: "row", alignItems: "center", gap: 11, marginTop: 19 }, inviteIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF22", alignItems: "center", justifyContent: "center" }, inviteCopy: { flex: 1 }, inviteTitle: { fontSize: 15, fontWeight: "800" }, inviteText: { fontSize: 12, lineHeight: 17, marginTop: 3 }, sectionRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 25, marginBottom: 11 }, sectionTitle: { fontSize: 18, fontWeight: "800" }, seeAll: { fontSize: 12, fontWeight: "800" }, community: { flexDirection: "row", alignItems: "center", padding: 13, borderRadius: 17, borderWidth: 1, marginBottom: 9 }, communityIcon: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center", marginRight: 11 }, communityInitial: { color: "#FFF", fontSize: 18, fontWeight: "800" }, communityCopy: { flex: 1 }, communityName: { fontSize: 14, fontWeight: "800" }, communityMeta: { fontSize: 12, marginTop: 4 }, empty: { borderWidth: 1, borderStyle: "dashed", borderRadius: 18, padding: 22, marginTop: 11, alignItems: "center", gap: 7 }, emptyTitle: { fontSize: 14, fontWeight: "800" }, emptyText: { textAlign: "center", fontSize: 12, lineHeight: 17 },
});
