-- Defense-in-depth: RLS policies still decide row access, but table grants decide
-- whether a role can reach the table at all. Remove anonymous reachability from
-- sensitive application tables and remove client-side write privileges that are
-- intentionally mediated by RLS/RPC/server workflows.

revoke all on table public.business_members from anon;
revoke all on table public.business_invitations from anon;
revoke all on table public.business_verification_requests from anon;
revoke all on table public.payment_orders from anon;
revoke all on table public.personal_identities from anon;
revoke all on table public.platform_admins from anon;
revoke all on table public.notifications from anon;
revoke all on table public.reports from anon;
revoke all on table public.saved_posts from anon;
revoke all on table public.blocks from anon;
revoke all on table public.buddy_requests from anon;
revoke all on table public.yoco_webhook_subscriptions from anon;

-- Invitations are created through the privileged business invitation function;
-- authenticated clients only need to read relevant invitations and update them
-- through the existing invitation acceptance/update paths.
revoke insert, delete on table public.business_invitations from authenticated;

-- Payment orders are created/attached through server-checked functions and are
-- read-only from the client once created.
revoke insert, update, delete on table public.payment_orders from authenticated;

-- Verification requests are submitted/reviewed through dedicated functions;
-- clients retain only the SELECT surface and the existing requester withdrawal
-- UPDATE policy.
revoke delete on table public.business_verification_requests from authenticated;

-- Notifications are generated by trusted triggers/functions. A client can only
-- read/update its own rows under the existing RLS policies.
revoke insert, delete on table public.notifications from authenticated;

-- Platform-admin metadata is read-only to authenticated users and filtered by RLS.
revoke insert, update, delete on table public.platform_admins from authenticated;

-- Webhook subscription metadata is admin-read only; no client-side mutation.
revoke insert, update, delete on table public.yoco_webhook_subscriptions from authenticated;

-- Reports can be created and reviewed by policy, but arbitrary deletion is not a
-- client operation.
revoke delete on table public.reports from authenticated;
